### ISSUE TITLE
How do I cancel italics

### ISSUE THREAD

**Issue by Mr-xue** [n0rmand0/Mariana-Pro-color-theme#19]
I want cancel italics, but I don't know how to do.
<img width="274" alt="iShot_2022-06-21_09 27 06" src="https://user-images.githubusercontent.com/11676811/174697494-6a124f82-2565-4ef5-84a5-f3d91450b5ff.png">

**Comment by monokai-681** [comment]
是的，这个移植过来的主题严重overuse斜体了，之前更新过一次修正了一下，但还是斜体是在太多。

theme我也不太懂，我很早以前自己编辑了一点点配置文件，有些斜体改过来了，但有些还是不行。只能凑合。

Yes, this theme overuses italics. A previous patch reduced some italics but it's still to much than actually needed.
