### ISSUE TITLE
Errors have wavy underline and another double solid underline

### ISSUE THREAD

**Issue by ondras** [n0rmand0/Mariana-Pro-color-theme#4]
Errors are way too underlined -- they have both the red wavy underline and a red double-straight-line underline. This happens in all three theme variants.

I would suggest removing the double straight underline, leaving in only the wavy underline.

**Comment by n0rmand0** [comment]
I pushed an update for this that should just keep the single squiggly line.

**Comment by ondras** [comment]
Thanks!
