### ISSUE TITLE
VScode updated and some texts became yellow

### ISSUE THREAD

**Issue by dfantonio** [n0rmand0/Mariana-Pro-color-theme#5]
Today my VScode updated to 1.43.0 and some parts of the code that were white got yellow:
![image](https://user-images.githubusercontent.com/40124768/76447750-f63b6f80-63a7-11ea-8ffc-c0fea09be02f.png)

I tested with others themes and they are white as always, so I'm guessing it's some problem with your theme.
 Mariana Pro Cool is some of the best theme i've found to VScode, but this yellow variables are really annoying :/

**Comment by n0rmand0** [comment]
Thanks for pointing that out.  I pushed out an update, give it a try.

**Comment by dfantonio** [comment]
It's working now!!!
Thanks for fixing this so fast.
