### ISSUE TITLE
JSX now displays the same colour for react components and HTML elements

### ISSUE THREAD

**Issue by tophergd** [n0rmand0/Mariana-Pro-color-theme#7]
JSX is now displaying the same colour for React components and HTML elements. I'm unsure if this was intentional or not, feel free to close the issue if so. 

I think this is after the recent JS fix that was merged: https://github.com/n0rmand0/Mariana-Pro-color-theme/commit/c5625295405d12a7855dc2f4c3e3aa9c7cef0550

Before, React components were blue as can be seen in your VSCode Extensions screenshots. 

The screenshot below shows JSX and HTML elements as red, having the difference was nice before 😀 

![Screen Shot 2020-03-16 at 18 21 02](https://user-images.githubusercontent.com/19024691/76788521-fb872880-67b2-11ea-9de7-90050d48812c.png)

**Comment by tophergd** [comment]
I think that the same change mentioned above also affected the way that built-in objects are coloured (console, Date) etc. They used to be blue but are now white which leaves them a little non-descript.

**Comment by n0rmand0** [comment]
I added the blue color back for classes and types.  Sorry!  I was trying to fix some changes in the new version of VS Code.
