### ISSUE TITLE
What's the yellow problem outlined in the commit?

### ISSUE THREAD

**Issue by chenglou** [n0rmand0/Mariana-Pro-color-theme#9]
Hello @n0rmand0. I was wondering about this commit: https://github.com/n0rmand0/Mariana-Pro-color-theme/commit/c5625295405d12a7855dc2f4c3e3aa9c7cef0550

This is the best vscode Mariana theme I've found; though unlike Sublime Text, entities aren't highlighted. Traced back to that commit.

Thanks!

**Comment by n0rmand0** [comment]
Can you give me an example of the language and entity that is an issue now?

**Comment by chenglou** [comment]
In Sublime Text, such entity is highlighted so:

<img width="411" alt="image" src="https://user-images.githubusercontent.com/1909539/107110188-ac971700-67fa-11eb-825a-69f3daada323.png">

While we're at it the `module` tagged as `keyword` is highlighted too above.

In VSCode:

<img width="484" alt="Screen Shot 2021-02-05 at 9 41 29 PM" src="https://user-images.githubusercontent.com/1909539/107110208-e9fba480-67fa-11eb-96b3-64b0a1959283.png">

Mariana Sublime Text source code: https://github.com/twolfson/sublime-files/blob/8905dd70bf5b9cef104a5fce9c79daea4bd24611/Packages/Color%20Scheme%20-%20Default/Mariana.sublime-color-scheme#L140

https://github.com/twolfson/sublime-files/blob/8905dd70bf5b9cef104a5fce9c79daea4bd24611/Packages/Color%20Scheme%20-%20Default/Mariana.sublime-color-scheme#L89

**Comment by n0rmand0** [comment]
I made the entity.name yellow again.  I don't think I am using the same syntax as you, so I'm not sure if it fixed.  Can you try version 3.0.10?

**Comment by chenglou** [comment]
Thanks, though that wouldn't work, since VSCode's doesn't support TextMate's scope exclusion syntax that you're using: https://github.com/microsoft/vscode-textmate/issues/52

So maybe it's easier to reduce that to just `entity.name`, aka highlight all of them.

This is the same reason `keyword` isn't highlighted in my second screenshot: https://github.com/n0rmand0/Mariana-Pro-color-theme/blob/f15f0720d5afe565846081e72a643ee5776e33a7/src/MarianaPro-color-theme.js#L329

**Comment by n0rmand0** [comment]
Thanks for the help.  Try 3.0.11.

**Comment by chenglou** [comment]
Long fixed. This theme is now on our recommended list for our language. Thanks =)
